export const RESET_SESSION = 'RESET_SESSION';

export const SHOW_LOADING_MODAL = 'SHOW_LOADING_MODAL';
export const HIDE_LOADING_MODAL = 'HIDE_LOADING_MODAL';

export const RESET_BEER_LIST = 'RESET_BEER_LIST';
export const RESET_BEER_DETAIL = 'RESET_BEER_DETAIL';
export const GET_BEER_LIST = 'GET_BEER_LIST';
export const GET_BEER_BY_ID = 'GET_BEER_BY_ID';
